### ISSUE TITLE
New ICD value for Iceland: 0196

### ISSUE THREAD

**Issue by phax** [CenPC434/validation#82]
Originally requested for PEPPOL.
[ICD_certificate_0196--20181026141807.pdf](https://github.com/CenPC434/validation/files/2523002/ICD_certificate_0196--20181026141807.pdf)

**Comment by oriol** [comment]
Done in UBL for rules BR-CL-10, BR-CL-11 and BR-CL-21

**Comment by oriol** [comment]
Done for CII
