### ISSUE TITLE
New ICD value for Singapore: 0195

### ISSUE THREAD

**Issue by phax** [CenPC434/validation#83]
I know that this might not be relevant to us, but for the sake of completeness: 0195
[ICD_certificate_0195--20180812164927.pdf](https://github.com/CenPC434/validation/files/2523004/ICD_certificate_0195--20180812164927.pdf)

**Comment by oriol** [comment]
resolved in UBL, applied to rules  BR-CL-10, BR-CL-11 and BR-CL-21

**Comment by oriol** [comment]
Added code in CII
